# API 응답 code 상수 (ApiCode enum). 성공 계열은 기본 OK로 통일, 오류·분기 필수 코드만 유지.
from enum import StrEnum


class ApiCode(StrEnum):
    # --- 공통 성공 ---
    OK = "OK"
    # --- Auth (로그인/가입/토큰 등 엔트리 포인트 구분) ---
    SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
    AUTH_SUCCESS = "AUTH_SUCCESS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    NICKNAME_ALREADY_EXISTS = "NICKNAME_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    # --- Users / Dogs ---
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_WITHDRAWN = "USER_WITHDRAWN"
    DOG_UPDATED = "DOG_UPDATED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    # --- Posts ---
    POST_NOT_FOUND = "POST_NOT_FOUND"
    POST_FILE_LIMIT_EXCEEDED = "POST_FILE_LIMIT_EXCEEDED"
    POST_HASHTAG_LIMIT_EXCEEDED = "POST_HASHTAG_LIMIT_EXCEEDED"
    LIKE_NOT_FOUND = "LIKE_NOT_FOUND"
    ALREADY_LIKED = "ALREADY_LIKED"
    CONFLICT = "CONFLICT"
    FORBIDDEN = "FORBIDDEN"
    # --- Comments ---
    COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND"
    INVALID_POSTID_FORMAT = "INVALID_POSTID_FORMAT"
    # --- Chat ---
    DM_SAME_USER = "DM_SAME_USER"
    # --- 요청/검증 (공통·미디어 등) ---
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    INVALID_PASSWORD_FORMAT = "INVALID_PASSWORD_FORMAT"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
    INVALID_IMAGE_FILE = "INVALID_IMAGE_FILE"
    SIGNUP_IMAGE_TOKEN_INVALID = "SIGNUP_IMAGE_TOKEN_INVALID"
    SIGNUP_IMAGE_TOKEN_ALREADY_USED = "SIGNUP_IMAGE_TOKEN_ALREADY_USED"
    # --- 전역/기타 ---
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    LOGIN_RATE_LIMIT_EXCEEDED = "LOGIN_RATE_LIMIT_EXCEEDED"
    CONSTRAINT_ERROR = "CONSTRAINT_ERROR"
    DB_ERROR = "DB_ERROR"
    HTTP_ERROR = "HTTP_ERROR"
    # --- Reports ---
    ALREADY_REPORTED = "ALREADY_REPORTED"


# 유니크 제약(23505) 위반 시 제약명 부분 문자열 → 409 응답 코드. 매칭 없으면 CONFLICT.
# 도메인이 사용자 노출용 유니크 제약을 늘리면 전역 핸들러 대신 이 테이블에 추가한다.
UNIQUE_CONSTRAINT_CODES: tuple[tuple[str, ApiCode], ...] = (
    ("email", ApiCode.EMAIL_ALREADY_EXISTS),
    ("nickname", ApiCode.NICKNAME_ALREADY_EXISTS),
)
